using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;

namespace CodeGenerator
{
    partial class Program
    {
        static HashSet<string> SkippedAncestors = new HashSet<string>() { "Object", "ValueType", "__ComObject" };

        // The methods with the next name will be skipped always
        static HashSet<string> SkippedMethodsNames = new HashSet<string>() { "get_Item" };

        // The methods with the next name prefixes will be skipped always
        static HashSet<string> SkippedMethodsPrefixes = new HashSet<string>() { "add_", "remove_", "Finalize" };

        // The methods with the next name prefixes will be skipped if they have the specified number of input arguments
        // (otherwise, only corresponding properties will be created)
        static Tuple<string, int>[] SkippedMethodsPrefixesNumArgs = new Tuple<string, int>[] { Tuple.Create("get_", 0), Tuple.Create("set_", 1) };

        static HashSet<string> ObjectMethods = new HashSet<string>() { "Equals", "GetHashCode", "GetType", "ToString" };

        static HashSet<string> IEnumerableMethods = new HashSet<string>() { "GetEnumerator" };

        static StreamWriter File;
        static StreamWriter DCEvHndlrFile;

        // Set this to False to get type names in short form, e.g. "int" instead of "Int32"
        static bool QuickTestMode = true;

        static void Main(string[] args)
        {
            string path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            string assmPath = Path.Combine(path, "Interop.CQG.dll");
            var assm = Assembly.LoadFrom(assmPath);

            string outPath = Path.GetFullPath(path + @"..\..\..\..\CQGLibrary\CQGLibrary.cs");
            string dcOutPath = Path.GetFullPath(path + @"..\..\..\..\..\DataCollectionForRealtime\DataCollectionForRealtime\CQGEventHandlers.cs");

            CurrentIndent = 1;
            InitIndents();

            using (File = new StreamWriter(outPath))
            using (DCEvHndlrFile = new StreamWriter(dcOutPath))
            {
                CreateWarningHeader(File);

                File.WriteLine("using System;");
                File.WriteLine("using System.Collections;");
                File.WriteLine("using System.Runtime.Remoting;");
                File.WriteLine("using FakeCQG.Models;");
                File.WriteLine("");
                File.WriteLine("namespace FakeCQG");
                File.WriteLine("{");

                CreateWarningHeader(DCEvHndlrFile);

                DCEvHndlrFile.WriteLine("using System;");
                DCEvHndlrFile.WriteLine("using FakeCQG;");
                DCEvHndlrFile.WriteLine("");
                DCEvHndlrFile.WriteLine("namespace DataCollectionForRealtime");
                DCEvHndlrFile.WriteLine("{");
                DCEvHndlrFile.WriteLine(Indent1 + "class CQGEventHandlers");
                DCEvHndlrFile.WriteLine(Indent1 + "{");

                CreateTypes(assm.ExportedTypes);

                File.WriteLine("}");

                DCEvHndlrFile.WriteLine(Indent1 + "}");
                DCEvHndlrFile.WriteLine("}");
            }
        }

        static void CreateWarningHeader(StreamWriter file)
        {
            file.WriteLine("// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING");
            file.WriteLine("// WARNING                                                                         WARNING");
            file.WriteLine("// WARNING    THIS .CS FILE WAS AUTOGENERATED!                                     WARNING");
            file.WriteLine("// WARNING    DO NOT EDIT IT BY HAND, BECAUSE ALL YOUR CHANGES WILL BE LOST!       WARNING");
            file.WriteLine("// WARNING    MAKE ALL CHANGES DIRECTLY TO THE FILE GENERATOR CODE!                WARNING");
            file.WriteLine("// WARNING                                                                         WARNING");
            file.WriteLine("// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING");
            file.WriteLine("");
            file.WriteLine("// Disable two warnings caused by CQG API specific:");
            file.WriteLine("// CS3003: Type of 'variable' is not CLS-compliant");
            file.WriteLine("// CS3008: Identifier 'identifier' differing only in case is not CLS-compliant");
            file.WriteLine("#pragma warning disable 3003, 3008");
            file.WriteLine("");
        }
    }
}
