// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
// WARNING                                                                         WARNING
// WARNING    THIS .CS FILE WAS AUTOGENERATED!                                     WARNING
// WARNING    DO NOT EDIT IT BY HAND, BECAUSE ALL YOUR CHANGES WILL BE LOST!       WARNING
// WARNING    MAKE ALL CHANGES DIRECTLY TO THE FILE GENERATOR CODE!                WARNING
// WARNING                                                                         WARNING
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

// Disable two warnings caused by CQG API specific:
// CS3003: Type of 'variable' is not CLS-compliant
// CS3008: Identifier 'identifier' differing only in case is not CLS-compliant
#pragma warning disable 3003, 3008

using System;
using System.Collections.Generic;

namespace DataCollectionForRealtime
{
    class CQGEventHandlers
    {
        public static void _ICQGCELEvents_AccountChangedEventHandlerImpl(CQG.eAccountChangeType change_type, CQG.CQGAccount cqg_account, CQG.CQGPosition cqg_position)
        {
            string name = "_ICQGCELEvents_AccountChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = change_type;
            nonSerArgs[1] = cqg_account;
            nonSerArgs[2] = cqg_position;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyAddedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study)
        {
            string name = "_ICQGCELEvents_AdvancedStudyAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandlerImpl(CQG.CQGAdvancedStudyDefinitions cqg_advanced_study_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study_definitions;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyInsertedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyRemovedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyResolvedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AdvancedStudyResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AdvancedStudyUpdatedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_advanced_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderPlacedEventHandlerImpl(string guid_, CQG.CQGAlgorithmicOrderParameters main_params, CQG.CQGAlgorithmicOrderProperties custom_props)
        {
            string name = "_ICQGCELEvents_AlgorithmicOrderPlacedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = guid_;
            nonSerArgs[1] = main_params;
            nonSerArgs[2] = custom_props;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandlerImpl(string guid_, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = guid_;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AllOrdersCanceledEventHandlerImpl(CQG.eOrderSideFilter order_side, CQG.CQGIntegerCollection gw_account_ids, CQG.CQGStringCollection instrument_names)
        {
            string name = "_ICQGCELEvents_AllOrdersCanceledEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = order_side;
            nonSerArgs[1] = gw_account_ids;
            nonSerArgs[2] = instrument_names;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_AuthenticationStatusChangedEventHandlerImpl(CQG.eSessionStatus new_status, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AuthenticationStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_BarsTimestampsResolvedEventHandlerImpl(CQG.CQGBarsTimestamps cqg_bars_timestamps, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_BarsTimestampsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_bars_timestamps;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_CELStartedEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_CommodityInstrumentsResolvedEventHandlerImpl(string commodity_name, CQG.eInstrumentType instrument_types, CQG.CQGCommodityInstruments cqg_commodity_intruments)
        {
            string name = "_ICQGCELEvents_CommodityInstrumentsResolvedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = commodity_name;
            serArgs[1] = instrument_types;
            nonSerArgs[2] = cqg_commodity_intruments;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionAddedEventHandlerImpl(CQG.CQGCondition cqg_condition)
        {
            string name = "_ICQGCELEvents_ConditionAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionDefinitionsResolvedEventHandlerImpl(CQG.CQGConditionDefinitions cqg_condition_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConditionDefinitionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition_definitions;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionInsertedEventHandlerImpl(CQG.CQGCondition cqg_condition, int index_)
        {
            string name = "_ICQGCELEvents_ConditionInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionRemovedEventHandlerImpl(CQG.CQGCondition cqg_condition, int index_)
        {
            string name = "_ICQGCELEvents_ConditionRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionResolvedEventHandlerImpl(CQG.CQGCondition cqg_condition, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConditionResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConditionUpdatedEventHandlerImpl(CQG.CQGCondition cqg_condition, int index_)
        {
            string name = "_ICQGCELEvents_ConditionUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_condition;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsAddedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_constant_volume_bars;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsInsertedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_constant_volume_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsRemovedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_constant_volume_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsResolvedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_constant_volume_bars;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_constant_volume_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CurrencyRatesChangedEventHandlerImpl(CQG.CQGCurrencyRates cqg_currency_rates)
        {
            string name = "_ICQGCELEvents_CurrencyRatesChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_currency_rates;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomSessionsResolvedEventHandlerImpl(CQG.CQGSessionsCollection cqg_sessions_collection, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomSessionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_sessions_collection;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyAddedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study)
        {
            string name = "_ICQGCELEvents_CustomStudyAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandlerImpl(CQG.CQGCustomStudyDefinitions cqg_custom_study_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study_definitions;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyInsertedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, int index_)
        {
            string name = "_ICQGCELEvents_CustomStudyInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyRemovedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, int index_)
        {
            string name = "_ICQGCELEvents_CustomStudyRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyResolvedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomStudyResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_CustomStudyUpdatedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, int index_)
        {
            string name = "_ICQGCELEvents_CustomStudyUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_custom_study;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_DataConnectionStatusChangedEventHandlerImpl(CQG.eConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_DataConnectionStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_DataErrorEventHandlerImpl(object cqg_error, string error_description)
        {
            string name = "_ICQGCELEvents_DataErrorEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = cqg_error;
            serArgs[1] = error_description;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_DataSourcesResolvedEventHandlerImpl(CQG.CQGDataSources cqg_data_sources, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_DataSourcesResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_data_sources;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_DataSourceSymbolsResolvedEventHandlerImpl(string data_source_abbreviation, CQG.CQGDataSourceSymbols cqg_data_source_symbols, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_DataSourceSymbolsResolvedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = data_source_abbreviation;
            nonSerArgs[1] = cqg_data_source_symbols;
            nonSerArgs[2] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ExpressionAddedEventHandlerImpl(CQG.CQGExpression cqg_expression)
        {
            string name = "_ICQGCELEvents_ExpressionAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_expression;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ExpressionInsertedEventHandlerImpl(CQG.CQGExpression cqg_expression, int index_)
        {
            string name = "_ICQGCELEvents_ExpressionInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_expression;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ExpressionRemovedEventHandlerImpl(CQG.CQGExpression cqg_expression, int index_)
        {
            string name = "_ICQGCELEvents_ExpressionRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_expression;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ExpressionResolvedEventHandlerImpl(CQG.CQGExpression cqg_expression, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ExpressionResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_expression;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ExpressionUpdatedEventHandlerImpl(CQG.CQGExpression cqg_expression, int index_)
        {
            string name = "_ICQGCELEvents_ExpressionUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_expression;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_GWConnectionStatusChangedEventHandlerImpl(CQG.eConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_GWConnectionStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_GWEnvironmentChangedEventHandlerImpl(CQG.eGWEnvChangeCode event_code, int account_id, int phase_)
        {
            string name = "_ICQGCELEvents_GWEnvironmentChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = event_code;
            serArgs[1] = account_id;
            serArgs[2] = phase_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_HistoricalSessionsResolvedEventHandlerImpl(CQG.CQGSessionsCollection cqg_historical_sessions, CQG.CQGHistoricalSessionsRequest cqg_historical_sessions_request, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_HistoricalSessionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_historical_sessions;
            nonSerArgs[1] = cqg_historical_sessions_request;
            nonSerArgs[2] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ICConnectionStatusChangedEventHandlerImpl(CQG.eICConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_ICConnectionStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_IncorrectSymbolEventHandlerImpl(string symbol_)
        {
            string name = "_ICQGCELEvents_IncorrectSymbolEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = symbol_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_InstrumentChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGQuotes cqg_quotes, CQG.CQGInstrumentProperties cqg_instrument_properties)
        {
            string name = "_ICQGCELEvents_InstrumentChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_instrument;
            nonSerArgs[1] = cqg_quotes;
            nonSerArgs[2] = cqg_instrument_properties;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_InstrumentDOMChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGDOMQuotes prev_asks, CQG.CQGDOMQuotes prev_bids)
        {
            string name = "_ICQGCELEvents_InstrumentDOMChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_instrument;
            nonSerArgs[1] = prev_asks;
            nonSerArgs[2] = prev_bids;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_InstrumentsGroupChangedEventHandlerImpl(CQG.eChangeType change_type, CQG.CQGInstrumentsGroup instruments_group, CQG.CQGStringCollection instruments_names)
        {
            string name = "_ICQGCELEvents_InstrumentsGroupChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = change_type;
            nonSerArgs[1] = instruments_group;
            nonSerArgs[2] = instruments_names;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_InstrumentsGroupResolvedEventHandlerImpl(CQG.CQGInstrumentsGroup instruments_group, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_InstrumentsGroupResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = instruments_group;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_InstrumentSubscribedEventHandlerImpl(string symbol_, CQG.CQGInstrument cqg_instrument)
        {
            string name = "_ICQGCELEvents_InstrumentSubscribedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = symbol_;
            nonSerArgs[1] = cqg_instrument;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_IsReadyEventHandlerImpl(ref CQG.eReadyStatus ready_status)
        {
            string name = "_ICQGCELEvents_IsReadyEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = ready_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            string name = "_ICQGCELEvents_LineTimeChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_line_time;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELEvents_ManualFillChangedEventHandlerImpl(CQG.CQGManualFill cqg_manual_fill, CQG.eManualFillUpdateType modify_type)
        {
            string name = "_ICQGCELEvents_ManualFillChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_manual_fill;
            serArgs[1] = modify_type;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ManualFillsResolvedEventHandlerImpl(CQG.CQGManualFills cqg_manual_fills, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ManualFillsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_manual_fills;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_ManualFillUpdateResolvedEventHandlerImpl(CQG.CQGManualFillRequest cqg_manual_fill_request, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ManualFillUpdateResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_manual_fill_request;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_OnIdleEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_OnQueryProgressEventHandlerImpl(CQG.CQGOrdersQuery cqg_orders_query, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_OnQueryProgressEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_orders_query;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_OrderChangedEventHandlerImpl(CQG.eChangeType change_type, CQG.CQGOrder cqg_order, CQG.CQGOrderProperties old_properties, CQG.CQGFill cqg_fill, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_OrderChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = change_type;
            nonSerArgs[1] = cqg_order;
            nonSerArgs[2] = old_properties;
            nonSerArgs[3] = cqg_fill;
            nonSerArgs[4] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PasswordChangedEventHandlerImpl(CQG.eSessionStatus request_status, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PasswordChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = request_status;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsAddedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_point_and_figure_bars;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsInsertedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_point_and_figure_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsRemovedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_point_and_figure_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsResolvedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_point_and_figure_bars;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsUpdatedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_point_and_figure_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_PositionsStatementResolvedEventHandlerImpl(CQG.CQGPositionsStatement cqg_positions_statement, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PositionsStatementResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_positions_statement;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_QFormulaDefinitionsResolvedEventHandlerImpl(CQG.CQGQFormulaDefinitions cqg_qformula_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_QFormulaDefinitionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_qformula_definitions;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_StrategyDefinitionProgressEventHandlerImpl(CQG.CQGStrategyDefinition cqg_definition, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_StrategyDefinitionProgressEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_definition;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SubMinuteBarsAddedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_submintue_bars)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_submintue_bars;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SubMinuteBarsInsertedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_subminute_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SubMinuteBarsRemovedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_subminute_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SubMinuteBarsResolvedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminte_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_subminte_bars;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SubMinuteBarsUpdatedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_subminute_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_SummariesStatementResolvedEventHandlerImpl(CQG.CQGSummariesStatement cqg_summaries_statement, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_SummariesStatementResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_summaries_statement;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TFlowBarsAddedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars)
        {
            string name = "_ICQGCELEvents_TFlowBarsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_tflow_bars;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TFlowBarsInsertedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, int index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_tflow_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TFlowBarsRemovedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, int index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_tflow_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TFlowBarsResolvedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TFlowBarsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_tflow_bars;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TFlowBarsUpdatedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, int index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_tflow_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TicksAddedEventHandlerImpl(CQG.CQGTicks cqg_ticks, int added_ticks_count)
        {
            string name = "_ICQGCELEvents_TicksAddedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_ticks;
            serArgs[1] = added_ticks_count;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TicksResolvedEventHandlerImpl(CQG.CQGTicks cqg_ticks, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TicksResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_ticks;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TimedBarsAddedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars)
        {
            string name = "_ICQGCELEvents_TimedBarsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_timed_bars;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TimedBarsInsertedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, int index_)
        {
            string name = "_ICQGCELEvents_TimedBarsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_timed_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TimedBarsRemovedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, int index_)
        {
            string name = "_ICQGCELEvents_TimedBarsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_timed_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TimedBarsResolvedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TimedBarsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_timed_bars;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TimedBarsUpdatedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, int index_)
        {
            string name = "_ICQGCELEvents_TimedBarsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_timed_bars;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradableCommoditiesResolvedEventHandlerImpl(int gw_account_id, CQG.CQGCommodities cqg_commodities, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradableCommoditiesResolvedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = gw_account_id;
            nonSerArgs[1] = cqg_commodities;
            nonSerArgs[2] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradableExchangesResolvedEventHandlerImpl(int gw_account_id, CQG.CQGExchanges cqg_exchanges, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradableExchangesResolvedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = gw_account_id;
            nonSerArgs[1] = cqg_exchanges;
            nonSerArgs[2] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemAddNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemAddInfo cqg_trading_system_add_info)
        {
            string name = "_ICQGCELEvents_TradingSystemAddNotificationEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_trading_system_add_info;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandlerImpl(CQG.CQGTradingSystemDefinitions cqg_trading_system_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system_definitions;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemInsertNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemInsertInfo cqg_trading_system_insert_info)
        {
            string name = "_ICQGCELEvents_TradingSystemInsertNotificationEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_trading_system_insert_info;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemRemoveNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemRemoveInfo cqg_trading_system_remove_info)
        {
            string name = "_ICQGCELEvents_TradingSystemRemoveNotificationEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_trading_system_remove_info;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemResolvedEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradingSystemResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemRelationAddInfo cqg_trading_system_relation_add_info)
        {
            string name = "_ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_trading_system_relation_add_info;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_TradingSystemUpdateNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemUpdateInfo cqg_trading_system_update_info)
        {
            string name = "_ICQGCELEvents_TradingSystemUpdateNotificationEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_trading_system;
            nonSerArgs[1] = cqg_trading_system_update_info;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_YieldsAddedEventHandlerImpl(CQG.CQGYields cqg_yields)
        {
            string name = "_ICQGCELEvents_YieldsAddedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_yields;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_YieldsInsertedEventHandlerImpl(CQG.CQGYields cqg_yields, int index_)
        {
            string name = "_ICQGCELEvents_YieldsInsertedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_yields;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_YieldsRemovedEventHandlerImpl(CQG.CQGYields cqg_yields, int index_)
        {
            string name = "_ICQGCELEvents_YieldsRemovedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_yields;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_YieldsResolvedEventHandlerImpl(CQG.CQGYields cqg_yields, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_YieldsResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_yields;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELEvents_YieldsUpdatedEventHandlerImpl(CQG.CQGYields cqg_yields, int index_)
        {
            string name = "_ICQGCELEvents_YieldsUpdatedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_yields;
            serArgs[1] = index_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELGeneralEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_CELStartedEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELGeneralEvents_CurrencyRatesChangedEventHandlerImpl(CQG.CQGCurrencyRates cqg_currency_rates)
        {
            string name = "_ICQGCELGeneralEvents_CurrencyRatesChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_currency_rates;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandlerImpl(CQG.eConnectionStatus new_status)
        {
            string name = "_ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELGeneralEvents_DataErrorEventHandlerImpl(object cqg_error, string error_description)
        {
            string name = "_ICQGCELGeneralEvents_DataErrorEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = cqg_error;
            serArgs[1] = error_description;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandlerImpl(CQG.eConnectionStatus new_status)
        {
            string name = "_ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELGeneralEvents_IsReadyEventHandlerImpl(ref CQG.eReadyStatus ready_status)
        {
            string name = "_ICQGCELGeneralEvents_IsReadyEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = ready_status;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELGeneralEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            string name = "_ICQGCELGeneralEvents_LineTimeChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = new_line_time;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELGeneralEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_OnIdleEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandlerImpl(string commodity_name, CQG.eInstrumentType instrument_types, CQG.CQGCommodityInstruments cqg_commodity_intruments)
        {
            string name = "_ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = commodity_name;
            serArgs[1] = instrument_types;
            nonSerArgs[2] = cqg_commodity_intruments;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELInstrumentEvents_IncorrectSymbolEventHandlerImpl(string symbol_)
        {
            string name = "_ICQGCELInstrumentEvents_IncorrectSymbolEventHandler";
            var serArgs = new Dictionary<int, object>();
            serArgs[0] = symbol_;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGQuotes cqg_quotes, CQG.CQGInstrumentProperties cqg_instrument_properties)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_instrument;
            nonSerArgs[1] = cqg_quotes;
            nonSerArgs[2] = cqg_instrument_properties;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGDOMQuotes prev_asks, CQG.CQGDOMQuotes prev_bids)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = cqg_instrument;
            nonSerArgs[1] = prev_asks;
            nonSerArgs[2] = prev_bids;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandlerImpl(CQG.eChangeType change_type, CQG.CQGInstrumentsGroup instruments_group, CQG.CQGStringCollection instruments_names)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = change_type;
            nonSerArgs[1] = instruments_group;
            nonSerArgs[2] = instruments_names;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandlerImpl(CQG.CQGInstrumentsGroup instruments_group, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandler";
            var nonSerArgs = new Dictionary<int, object>();
            nonSerArgs[0] = instruments_group;
            nonSerArgs[1] = cqg_error;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, nonSerArgs: nonSerArgs);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentSubscribedEventHandlerImpl(string symbol_, CQG.CQGInstrument cqg_instrument)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentSubscribedEventHandler";
            var serArgs = new Dictionary<int, object>();
            var nonSerArgs = new Dictionary<int, object>();
            serArgs[0] = symbol_;
            nonSerArgs[1] = cqg_instrument;
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, serArgs: serArgs, nonSerArgs: nonSerArgs);
        }

    }
}
