// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
// WARNING                                                                         WARNING
// WARNING    THIS .CS FILE WAS AUTOGENERATED!                                     WARNING
// WARNING    DO NOT EDIT IT BY HAND, BECAUSE ALL YOUR CHANGES WILL BE LOST!       WARNING
// WARNING    MAKE ALL CHANGES DIRECTLY TO THE FILE GENERATOR CODE!                WARNING
// WARNING                                                                         WARNING
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

// Disable two warnings caused by CQG API specific:
// CS3003: Type of 'variable' is not CLS-compliant
// CS3008: Identifier 'identifier' differing only in case is not CLS-compliant
#pragma warning disable 3003, 3008

using System;
using FakeCQG;

namespace DataCollectionForRealtime
{
    class CQGEventHandlers
    {
        public static void _ICQGCELEvents_AccountChangedEventHandlerImpl(eAccountChangeType change_type, CQG.CQGAccount cqg_account, CQG.CQGPosition cqg_position)
        {
            string name = "_ICQGCELEvents_AccountChangedEventHandler";
            string cqg_accountKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_accountKey, cqg_account);
            string cqg_positionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_positionKey, cqg_position);
            var args = new object[] { change_type, cqg_accountKey, cqg_positionKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyAddedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study)
        {
            string name = "_ICQGCELEvents_AdvancedStudyAddedEventHandler";
            string cqg_advanced_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_studyKey, cqg_advanced_study);
            var args = new object[] { cqg_advanced_studyKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandlerImpl(CQG.CQGAdvancedStudyDefinitions cqg_advanced_study_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandler";
            string cqg_advanced_study_definitionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_study_definitionsKey, cqg_advanced_study_definitions);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_advanced_study_definitionsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyInsertedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyInsertedEventHandler";
            string cqg_advanced_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_studyKey, cqg_advanced_study);
            var args = new object[] { cqg_advanced_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyRemovedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyRemovedEventHandler";
            string cqg_advanced_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_studyKey, cqg_advanced_study);
            var args = new object[] { cqg_advanced_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyResolvedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AdvancedStudyResolvedEventHandler";
            string cqg_advanced_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_studyKey, cqg_advanced_study);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_advanced_studyKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyUpdatedEventHandlerImpl(CQG.CQGAdvancedStudy cqg_advanced_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_AdvancedStudyUpdatedEventHandler";
            string cqg_advanced_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_advanced_studyKey, cqg_advanced_study);
            var args = new object[] { cqg_advanced_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderPlacedEventHandlerImpl(String guid_, CQG.CQGAlgorithmicOrderParameters main_params, CQG.CQGAlgorithmicOrderProperties custom_props)
        {
            string name = "_ICQGCELEvents_AlgorithmicOrderPlacedEventHandler";
            string main_paramsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(main_paramsKey, main_params);
            string custom_propsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(custom_propsKey, custom_props);
            var args = new object[] { guid_, main_paramsKey, custom_propsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandlerImpl(String guid_, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandler";
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { guid_, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AllOrdersCanceledEventHandlerImpl(eOrderSideFilter order_side, CQG.CQGIntegerCollection gw_account_ids, CQG.CQGStringCollection instrument_names)
        {
            string name = "_ICQGCELEvents_AllOrdersCanceledEventHandler";
            string gw_account_idsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(gw_account_idsKey, gw_account_ids);
            string instrument_namesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instrument_namesKey, instrument_names);
            var args = new object[] { order_side, gw_account_idsKey, instrument_namesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AuthenticationStatusChangedEventHandlerImpl(eSessionStatus new_status, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_AuthenticationStatusChangedEventHandler";
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { new_status, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_BarsTimestampsResolvedEventHandlerImpl(CQG.CQGBarsTimestamps cqg_bars_timestamps, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_BarsTimestampsResolvedEventHandler";
            string cqg_bars_timestampsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_bars_timestampsKey, cqg_bars_timestamps);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_bars_timestampsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_CELStartedEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_CommodityInstrumentsResolvedEventHandlerImpl(String commodity_name, eInstrumentType instrument_types, CQG.CQGCommodityInstruments cqg_commodity_intruments)
        {
            string name = "_ICQGCELEvents_CommodityInstrumentsResolvedEventHandler";
            string cqg_commodity_intrumentsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_commodity_intrumentsKey, cqg_commodity_intruments);
            var args = new object[] { commodity_name, instrument_types, cqg_commodity_intrumentsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionAddedEventHandlerImpl(CQG.CQGCondition cqg_condition)
        {
            string name = "_ICQGCELEvents_ConditionAddedEventHandler";
            string cqg_conditionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_conditionKey, cqg_condition);
            var args = new object[] { cqg_conditionKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionDefinitionsResolvedEventHandlerImpl(CQG.CQGConditionDefinitions cqg_condition_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConditionDefinitionsResolvedEventHandler";
            string cqg_condition_definitionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_condition_definitionsKey, cqg_condition_definitions);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_condition_definitionsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionInsertedEventHandlerImpl(CQG.CQGCondition cqg_condition, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConditionInsertedEventHandler";
            string cqg_conditionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_conditionKey, cqg_condition);
            var args = new object[] { cqg_conditionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionRemovedEventHandlerImpl(CQG.CQGCondition cqg_condition, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConditionRemovedEventHandler";
            string cqg_conditionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_conditionKey, cqg_condition);
            var args = new object[] { cqg_conditionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionResolvedEventHandlerImpl(CQG.CQGCondition cqg_condition, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConditionResolvedEventHandler";
            string cqg_conditionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_conditionKey, cqg_condition);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_conditionKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionUpdatedEventHandlerImpl(CQG.CQGCondition cqg_condition, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConditionUpdatedEventHandler";
            string cqg_conditionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_conditionKey, cqg_condition);
            var args = new object[] { cqg_conditionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsAddedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsAddedEventHandler";
            string cqg_constant_volume_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_constant_volume_barsKey, cqg_constant_volume_bars);
            var args = new object[] { cqg_constant_volume_barsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsInsertedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsInsertedEventHandler";
            string cqg_constant_volume_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_constant_volume_barsKey, cqg_constant_volume_bars);
            var args = new object[] { cqg_constant_volume_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsRemovedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsRemovedEventHandler";
            string cqg_constant_volume_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_constant_volume_barsKey, cqg_constant_volume_bars);
            var args = new object[] { cqg_constant_volume_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsResolvedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsResolvedEventHandler";
            string cqg_constant_volume_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_constant_volume_barsKey, cqg_constant_volume_bars);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_constant_volume_barsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandlerImpl(CQG.CQGConstantVolumeBars cqg_constant_volume_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandler";
            string cqg_constant_volume_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_constant_volume_barsKey, cqg_constant_volume_bars);
            var args = new object[] { cqg_constant_volume_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CurrencyRatesChangedEventHandlerImpl(CQG.CQGCurrencyRates cqg_currency_rates)
        {
            string name = "_ICQGCELEvents_CurrencyRatesChangedEventHandler";
            string cqg_currency_ratesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_currency_ratesKey, cqg_currency_rates);
            var args = new object[] { cqg_currency_ratesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomSessionsResolvedEventHandlerImpl(CQG.CQGSessionsCollection cqg_sessions_collection, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomSessionsResolvedEventHandler";
            string cqg_sessions_collectionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_sessions_collectionKey, cqg_sessions_collection);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_sessions_collectionKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyAddedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study)
        {
            string name = "_ICQGCELEvents_CustomStudyAddedEventHandler";
            string cqg_custom_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_studyKey, cqg_custom_study);
            var args = new object[] { cqg_custom_studyKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandlerImpl(CQG.CQGCustomStudyDefinitions cqg_custom_study_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandler";
            string cqg_custom_study_definitionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_study_definitionsKey, cqg_custom_study_definitions);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_custom_study_definitionsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyInsertedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_CustomStudyInsertedEventHandler";
            string cqg_custom_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_studyKey, cqg_custom_study);
            var args = new object[] { cqg_custom_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyRemovedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_CustomStudyRemovedEventHandler";
            string cqg_custom_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_studyKey, cqg_custom_study);
            var args = new object[] { cqg_custom_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyResolvedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_CustomStudyResolvedEventHandler";
            string cqg_custom_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_studyKey, cqg_custom_study);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_custom_studyKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyUpdatedEventHandlerImpl(CQG.CQGCustomStudy cqg_custom_study, Int32 index_)
        {
            string name = "_ICQGCELEvents_CustomStudyUpdatedEventHandler";
            string cqg_custom_studyKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_custom_studyKey, cqg_custom_study);
            var args = new object[] { cqg_custom_studyKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_DataConnectionStatusChangedEventHandler";
            var args = new object[] { new_status };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataErrorEventHandlerImpl(Object cqg_error, String error_description)
        {
            string name = "_ICQGCELEvents_DataErrorEventHandler";
            var args = new object[] { cqg_error, error_description };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataSourcesResolvedEventHandlerImpl(CQG.CQGDataSources cqg_data_sources, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_DataSourcesResolvedEventHandler";
            string cqg_data_sourcesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_data_sourcesKey, cqg_data_sources);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_data_sourcesKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataSourceSymbolsResolvedEventHandlerImpl(String data_source_abbreviation, CQG.CQGDataSourceSymbols cqg_data_source_symbols, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_DataSourceSymbolsResolvedEventHandler";
            string cqg_data_source_symbolsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_data_source_symbolsKey, cqg_data_source_symbols);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { data_source_abbreviation, cqg_data_source_symbolsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionAddedEventHandlerImpl(CQG.CQGExpression cqg_expression)
        {
            string name = "_ICQGCELEvents_ExpressionAddedEventHandler";
            string cqg_expressionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_expressionKey, cqg_expression);
            var args = new object[] { cqg_expressionKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionInsertedEventHandlerImpl(CQG.CQGExpression cqg_expression, Int32 index_)
        {
            string name = "_ICQGCELEvents_ExpressionInsertedEventHandler";
            string cqg_expressionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_expressionKey, cqg_expression);
            var args = new object[] { cqg_expressionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionRemovedEventHandlerImpl(CQG.CQGExpression cqg_expression, Int32 index_)
        {
            string name = "_ICQGCELEvents_ExpressionRemovedEventHandler";
            string cqg_expressionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_expressionKey, cqg_expression);
            var args = new object[] { cqg_expressionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionResolvedEventHandlerImpl(CQG.CQGExpression cqg_expression, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ExpressionResolvedEventHandler";
            string cqg_expressionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_expressionKey, cqg_expression);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_expressionKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionUpdatedEventHandlerImpl(CQG.CQGExpression cqg_expression, Int32 index_)
        {
            string name = "_ICQGCELEvents_ExpressionUpdatedEventHandler";
            string cqg_expressionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_expressionKey, cqg_expression);
            var args = new object[] { cqg_expressionKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_GWConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_GWConnectionStatusChangedEventHandler";
            var args = new object[] { new_status };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_GWEnvironmentChangedEventHandlerImpl(eGWEnvChangeCode event_code, Int32 account_id, Int32 phase_)
        {
            string name = "_ICQGCELEvents_GWEnvironmentChangedEventHandler";
            var args = new object[] { event_code, account_id, phase_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_HistoricalSessionsResolvedEventHandlerImpl(CQG.CQGSessionsCollection cqg_historical_sessions, CQG.CQGHistoricalSessionsRequest cqg_historical_sessions_request, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_HistoricalSessionsResolvedEventHandler";
            string cqg_historical_sessionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_historical_sessionsKey, cqg_historical_sessions);
            string cqg_historical_sessions_requestKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_historical_sessions_requestKey, cqg_historical_sessions_request);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_historical_sessionsKey, cqg_historical_sessions_requestKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ICConnectionStatusChangedEventHandlerImpl(eICConnectionStatus new_status)
        {
            string name = "_ICQGCELEvents_ICConnectionStatusChangedEventHandler";
            var args = new object[] { new_status };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_IncorrectSymbolEventHandlerImpl(String symbol_)
        {
            string name = "_ICQGCELEvents_IncorrectSymbolEventHandler";
            var args = new object[] { symbol_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGQuotes cqg_quotes, CQG.CQGInstrumentProperties cqg_instrument_properties)
        {
            string name = "_ICQGCELEvents_InstrumentChangedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            string cqg_quotesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_quotesKey, cqg_quotes);
            string cqg_instrument_propertiesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrument_propertiesKey, cqg_instrument_properties);
            var args = new object[] { cqg_instrumentKey, cqg_quotesKey, cqg_instrument_propertiesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentDOMChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGDOMQuotes prev_asks, CQG.CQGDOMQuotes prev_bids)
        {
            string name = "_ICQGCELEvents_InstrumentDOMChangedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            string prev_asksKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(prev_asksKey, prev_asks);
            string prev_bidsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(prev_bidsKey, prev_bids);
            var args = new object[] { cqg_instrumentKey, prev_asksKey, prev_bidsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentsGroupChangedEventHandlerImpl(eChangeType change_type, CQG.CQGInstrumentsGroup instruments_group, CQG.CQGStringCollection instruments_names)
        {
            string name = "_ICQGCELEvents_InstrumentsGroupChangedEventHandler";
            string instruments_groupKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_groupKey, instruments_group);
            string instruments_namesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_namesKey, instruments_names);
            var args = new object[] { change_type, instruments_groupKey, instruments_namesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentsGroupResolvedEventHandlerImpl(CQG.CQGInstrumentsGroup instruments_group, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_InstrumentsGroupResolvedEventHandler";
            string instruments_groupKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_groupKey, instruments_group);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { instruments_groupKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentSubscribedEventHandlerImpl(String symbol_, CQG.CQGInstrument cqg_instrument)
        {
            string name = "_ICQGCELEvents_InstrumentSubscribedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            var args = new object[] { symbol_, cqg_instrumentKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_IsReadyEventHandlerImpl(ref CQG.eReadyStatus ready_status)
        {
            string name = "_ICQGCELEvents_IsReadyEventHandler";
            string ready_statusKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(ready_statusKey, ready_status);
            var args = new object[] { ready_statusKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            string name = "_ICQGCELEvents_LineTimeChangedEventHandler";
            var args = new object[] { new_line_time };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillChangedEventHandlerImpl(CQG.CQGManualFill cqg_manual_fill, eManualFillUpdateType modify_type)
        {
            string name = "_ICQGCELEvents_ManualFillChangedEventHandler";
            string cqg_manual_fillKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_manual_fillKey, cqg_manual_fill);
            var args = new object[] { cqg_manual_fillKey, modify_type };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillsResolvedEventHandlerImpl(CQG.CQGManualFills cqg_manual_fills, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ManualFillsResolvedEventHandler";
            string cqg_manual_fillsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_manual_fillsKey, cqg_manual_fills);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_manual_fillsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillUpdateResolvedEventHandlerImpl(CQG.CQGManualFillRequest cqg_manual_fill_request, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_ManualFillUpdateResolvedEventHandler";
            string cqg_manual_fill_requestKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_manual_fill_requestKey, cqg_manual_fill_request);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_manual_fill_requestKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_OnIdleEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_OnQueryProgressEventHandlerImpl(CQG.CQGOrdersQuery cqg_orders_query, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_OnQueryProgressEventHandler";
            string cqg_orders_queryKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_orders_queryKey, cqg_orders_query);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_orders_queryKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_OrderChangedEventHandlerImpl(eChangeType change_type, CQG.CQGOrder cqg_order, CQG.CQGOrderProperties old_properties, CQG.CQGFill cqg_fill, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_OrderChangedEventHandler";
            string cqg_orderKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_orderKey, cqg_order);
            string old_propertiesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(old_propertiesKey, old_properties);
            string cqg_fillKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_fillKey, cqg_fill);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { change_type, cqg_orderKey, old_propertiesKey, cqg_fillKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PasswordChangedEventHandlerImpl(eSessionStatus request_status, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PasswordChangedEventHandler";
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { request_status, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsAddedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsAddedEventHandler";
            string cqg_point_and_figure_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_point_and_figure_barsKey, cqg_point_and_figure_bars);
            var args = new object[] { cqg_point_and_figure_barsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsInsertedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsInsertedEventHandler";
            string cqg_point_and_figure_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_point_and_figure_barsKey, cqg_point_and_figure_bars);
            var args = new object[] { cqg_point_and_figure_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsRemovedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsRemovedEventHandler";
            string cqg_point_and_figure_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_point_and_figure_barsKey, cqg_point_and_figure_bars);
            var args = new object[] { cqg_point_and_figure_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsResolvedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsResolvedEventHandler";
            string cqg_point_and_figure_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_point_and_figure_barsKey, cqg_point_and_figure_bars);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_point_and_figure_barsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsUpdatedEventHandlerImpl(CQG.CQGPointAndFigureBars cqg_point_and_figure_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_PointAndFigureBarsUpdatedEventHandler";
            string cqg_point_and_figure_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_point_and_figure_barsKey, cqg_point_and_figure_bars);
            var args = new object[] { cqg_point_and_figure_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PositionsStatementResolvedEventHandlerImpl(CQG.CQGPositionsStatement cqg_positions_statement, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_PositionsStatementResolvedEventHandler";
            string cqg_positions_statementKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_positions_statementKey, cqg_positions_statement);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_positions_statementKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_QFormulaDefinitionsResolvedEventHandlerImpl(CQG.CQGQFormulaDefinitions cqg_qformula_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_QFormulaDefinitionsResolvedEventHandler";
            string cqg_qformula_definitionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_qformula_definitionsKey, cqg_qformula_definitions);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_qformula_definitionsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_StrategyDefinitionProgressEventHandlerImpl(CQG.CQGStrategyDefinition cqg_definition, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_StrategyDefinitionProgressEventHandler";
            string cqg_definitionKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_definitionKey, cqg_definition);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_definitionKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsAddedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_submintue_bars)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsAddedEventHandler";
            string cqg_submintue_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_submintue_barsKey, cqg_submintue_bars);
            var args = new object[] { cqg_submintue_barsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsInsertedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsInsertedEventHandler";
            string cqg_subminute_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_subminute_barsKey, cqg_subminute_bars);
            var args = new object[] { cqg_subminute_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsRemovedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsRemovedEventHandler";
            string cqg_subminute_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_subminute_barsKey, cqg_subminute_bars);
            var args = new object[] { cqg_subminute_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsResolvedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminte_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsResolvedEventHandler";
            string cqg_subminte_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_subminte_barsKey, cqg_subminte_bars);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_subminte_barsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsUpdatedEventHandlerImpl(CQG.CQGSubMinuteBars cqg_subminute_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_SubMinuteBarsUpdatedEventHandler";
            string cqg_subminute_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_subminute_barsKey, cqg_subminute_bars);
            var args = new object[] { cqg_subminute_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SummariesStatementResolvedEventHandlerImpl(CQG.CQGSummariesStatement cqg_summaries_statement, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_SummariesStatementResolvedEventHandler";
            string cqg_summaries_statementKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_summaries_statementKey, cqg_summaries_statement);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_summaries_statementKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsAddedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars)
        {
            string name = "_ICQGCELEvents_TFlowBarsAddedEventHandler";
            string cqg_tflow_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_tflow_barsKey, cqg_tflow_bars);
            var args = new object[] { cqg_tflow_barsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsInsertedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsInsertedEventHandler";
            string cqg_tflow_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_tflow_barsKey, cqg_tflow_bars);
            var args = new object[] { cqg_tflow_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsRemovedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsRemovedEventHandler";
            string cqg_tflow_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_tflow_barsKey, cqg_tflow_bars);
            var args = new object[] { cqg_tflow_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsResolvedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TFlowBarsResolvedEventHandler";
            string cqg_tflow_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_tflow_barsKey, cqg_tflow_bars);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_tflow_barsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsUpdatedEventHandlerImpl(CQG.CQGTFlowBars cqg_tflow_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TFlowBarsUpdatedEventHandler";
            string cqg_tflow_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_tflow_barsKey, cqg_tflow_bars);
            var args = new object[] { cqg_tflow_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TicksAddedEventHandlerImpl(CQG.CQGTicks cqg_ticks, Int32 added_ticks_count)
        {
            string name = "_ICQGCELEvents_TicksAddedEventHandler";
            string cqg_ticksKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_ticksKey, cqg_ticks);
            var args = new object[] { cqg_ticksKey, added_ticks_count };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TicksResolvedEventHandlerImpl(CQG.CQGTicks cqg_ticks, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TicksResolvedEventHandler";
            string cqg_ticksKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_ticksKey, cqg_ticks);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_ticksKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsAddedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars)
        {
            string name = "_ICQGCELEvents_TimedBarsAddedEventHandler";
            string cqg_timed_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_timed_barsKey, cqg_timed_bars);
            var args = new object[] { cqg_timed_barsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsInsertedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TimedBarsInsertedEventHandler";
            string cqg_timed_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_timed_barsKey, cqg_timed_bars);
            var args = new object[] { cqg_timed_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsRemovedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TimedBarsRemovedEventHandler";
            string cqg_timed_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_timed_barsKey, cqg_timed_bars);
            var args = new object[] { cqg_timed_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsResolvedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TimedBarsResolvedEventHandler";
            string cqg_timed_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_timed_barsKey, cqg_timed_bars);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_timed_barsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsUpdatedEventHandlerImpl(CQG.CQGTimedBars cqg_timed_bars, Int32 index_)
        {
            string name = "_ICQGCELEvents_TimedBarsUpdatedEventHandler";
            string cqg_timed_barsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_timed_barsKey, cqg_timed_bars);
            var args = new object[] { cqg_timed_barsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradableCommoditiesResolvedEventHandlerImpl(Int32 gw_account_id, CQG.CQGCommodities cqg_commodities, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradableCommoditiesResolvedEventHandler";
            string cqg_commoditiesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_commoditiesKey, cqg_commodities);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { gw_account_id, cqg_commoditiesKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradableExchangesResolvedEventHandlerImpl(Int32 gw_account_id, CQG.CQGExchanges cqg_exchanges, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradableExchangesResolvedEventHandler";
            string cqg_exchangesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_exchangesKey, cqg_exchanges);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { gw_account_id, cqg_exchangesKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemAddNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemAddInfo cqg_trading_system_add_info)
        {
            string name = "_ICQGCELEvents_TradingSystemAddNotificationEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_trading_system_add_infoKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_add_infoKey, cqg_trading_system_add_info);
            var args = new object[] { cqg_trading_systemKey, cqg_trading_system_add_infoKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandlerImpl(CQG.CQGTradingSystemDefinitions cqg_trading_system_definitions, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandler";
            string cqg_trading_system_definitionsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_definitionsKey, cqg_trading_system_definitions);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_trading_system_definitionsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemInsertNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemInsertInfo cqg_trading_system_insert_info)
        {
            string name = "_ICQGCELEvents_TradingSystemInsertNotificationEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_trading_system_insert_infoKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_insert_infoKey, cqg_trading_system_insert_info);
            var args = new object[] { cqg_trading_systemKey, cqg_trading_system_insert_infoKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemRemoveNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemRemoveInfo cqg_trading_system_remove_info)
        {
            string name = "_ICQGCELEvents_TradingSystemRemoveNotificationEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_trading_system_remove_infoKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_remove_infoKey, cqg_trading_system_remove_info);
            var args = new object[] { cqg_trading_systemKey, cqg_trading_system_remove_infoKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemResolvedEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_TradingSystemResolvedEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_trading_systemKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemRelationAddInfo cqg_trading_system_relation_add_info)
        {
            string name = "_ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_trading_system_relation_add_infoKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_relation_add_infoKey, cqg_trading_system_relation_add_info);
            var args = new object[] { cqg_trading_systemKey, cqg_trading_system_relation_add_infoKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemUpdateNotificationEventHandlerImpl(CQG.CQGTradingSystem cqg_trading_system, CQG.CQGTradingSystemUpdateInfo cqg_trading_system_update_info)
        {
            string name = "_ICQGCELEvents_TradingSystemUpdateNotificationEventHandler";
            string cqg_trading_systemKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_systemKey, cqg_trading_system);
            string cqg_trading_system_update_infoKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_trading_system_update_infoKey, cqg_trading_system_update_info);
            var args = new object[] { cqg_trading_systemKey, cqg_trading_system_update_infoKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsAddedEventHandlerImpl(CQG.CQGYields cqg_yields)
        {
            string name = "_ICQGCELEvents_YieldsAddedEventHandler";
            string cqg_yieldsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_yieldsKey, cqg_yields);
            var args = new object[] { cqg_yieldsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsInsertedEventHandlerImpl(CQG.CQGYields cqg_yields, Int32 index_)
        {
            string name = "_ICQGCELEvents_YieldsInsertedEventHandler";
            string cqg_yieldsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_yieldsKey, cqg_yields);
            var args = new object[] { cqg_yieldsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsRemovedEventHandlerImpl(CQG.CQGYields cqg_yields, Int32 index_)
        {
            string name = "_ICQGCELEvents_YieldsRemovedEventHandler";
            string cqg_yieldsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_yieldsKey, cqg_yields);
            var args = new object[] { cqg_yieldsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsResolvedEventHandlerImpl(CQG.CQGYields cqg_yields, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELEvents_YieldsResolvedEventHandler";
            string cqg_yieldsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_yieldsKey, cqg_yields);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { cqg_yieldsKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsUpdatedEventHandlerImpl(CQG.CQGYields cqg_yields, Int32 index_)
        {
            string name = "_ICQGCELEvents_YieldsUpdatedEventHandler";
            string cqg_yieldsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_yieldsKey, cqg_yields);
            var args = new object[] { cqg_yieldsKey, index_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_CELStartedEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELGeneralEvents_CurrencyRatesChangedEventHandlerImpl(CQG.CQGCurrencyRates cqg_currency_rates)
        {
            string name = "_ICQGCELGeneralEvents_CurrencyRatesChangedEventHandler";
            string cqg_currency_ratesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_currency_ratesKey, cqg_currency_rates);
            var args = new object[] { cqg_currency_ratesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            string name = "_ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandler";
            var args = new object[] { new_status };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_DataErrorEventHandlerImpl(Object cqg_error, String error_description)
        {
            string name = "_ICQGCELGeneralEvents_DataErrorEventHandler";
            var args = new object[] { cqg_error, error_description };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            string name = "_ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandler";
            var args = new object[] { new_status };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_IsReadyEventHandlerImpl(ref CQG.eReadyStatus ready_status)
        {
            string name = "_ICQGCELGeneralEvents_IsReadyEventHandler";
            string ready_statusKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(ready_statusKey, ready_status);
            var args = new object[] { ready_statusKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            string name = "_ICQGCELGeneralEvents_LineTimeChangedEventHandler";
            var args = new object[] { new_line_time };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_OnIdleEventHandler";
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name);
        }

        public static void _ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandlerImpl(String commodity_name, eInstrumentType instrument_types, CQG.CQGCommodityInstruments cqg_commodity_intruments)
        {
            string name = "_ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandler";
            string cqg_commodity_intrumentsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_commodity_intrumentsKey, cqg_commodity_intruments);
            var args = new object[] { commodity_name, instrument_types, cqg_commodity_intrumentsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_IncorrectSymbolEventHandlerImpl(String symbol_)
        {
            string name = "_ICQGCELInstrumentEvents_IncorrectSymbolEventHandler";
            var args = new object[] { symbol_ };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGQuotes cqg_quotes, CQG.CQGInstrumentProperties cqg_instrument_properties)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentChangedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            string cqg_quotesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_quotesKey, cqg_quotes);
            string cqg_instrument_propertiesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrument_propertiesKey, cqg_instrument_properties);
            var args = new object[] { cqg_instrumentKey, cqg_quotesKey, cqg_instrument_propertiesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandlerImpl(CQG.CQGInstrument cqg_instrument, CQG.CQGDOMQuotes prev_asks, CQG.CQGDOMQuotes prev_bids)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            string prev_asksKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(prev_asksKey, prev_asks);
            string prev_bidsKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(prev_bidsKey, prev_bids);
            var args = new object[] { cqg_instrumentKey, prev_asksKey, prev_bidsKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandlerImpl(eChangeType change_type, CQG.CQGInstrumentsGroup instruments_group, CQG.CQGStringCollection instruments_names)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandler";
            string instruments_groupKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_groupKey, instruments_group);
            string instruments_namesKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_namesKey, instruments_names);
            var args = new object[] { change_type, instruments_groupKey, instruments_namesKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandlerImpl(CQG.CQGInstrumentsGroup instruments_group, CQG.CQGError cqg_error)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandler";
            string instruments_groupKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(instruments_groupKey, instruments_group);
            string cqg_errorKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_errorKey, cqg_error);
            var args = new object[] { instruments_groupKey, cqg_errorKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentSubscribedEventHandlerImpl(String symbol_, CQG.CQGInstrument cqg_instrument)
        {
            string name = "_ICQGCELInstrumentEvents_InstrumentSubscribedEventHandler";
            string cqg_instrumentKey = FakeCQG.CQG.CreateUniqueKey();
            DataDictionaries.PutObjectToTheDictionary(cqg_instrumentKey, cqg_instrument);
            var args = new object[] { symbol_, cqg_instrumentKey };
            FakeCQG.CQG.AnswerHelper.CommonEventHandler(name, args);
        }

    }
}
