// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
// WARNING                                                                         WARNING
// WARNING    THIS .CS FILE WAS AUTOGENERATED!                                     WARNING
// WARNING    DO NOT EDIT IT BY HAND, BECAUSE ALL YOUR CHANGES WILL BE LOST!       WARNING
// WARNING    MAKE ALL CHANGES DIRECTLY TO THE FILE GENERATOR CODE!                WARNING
// WARNING                                                                         WARNING
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

// Disable two warnings caused by CQG API specific:
// CS3003: Type of 'variable' is not CLS-compliant
// CS3008: Identifier 'identifier' differing only in case is not CLS-compliant
#pragma warning disable 3003, 3008

using System;
using FakeCQG;

namespace DataCollectionForRealtime
{
    class CQGEventHandlers
    {
        public static void _ICQGCELEvents_AccountChangedEventHandlerImpl(eAccountChangeType change_type, CQGAccount cqg_account, CQGPosition cqg_position)
        {
            object[] args = new object[4] {"!", change_type, cqg_account, cqg_position};

            string name = "_ICQGCELEvents_AccountChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyAddedEventHandlerImpl(CQGAdvancedStudy cqg_advanced_study)
        {
            object[] args = new object[2] {"!", cqg_advanced_study};

            string name = "_ICQGCELEvents_AdvancedStudyAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandlerImpl(CQGAdvancedStudyDefinitions cqg_advanced_study_definitions, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_advanced_study_definitions, cqg_error};

            string name = "_ICQGCELEvents_AdvancedStudyDefinitionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyInsertedEventHandlerImpl(CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_advanced_study, index_};

            string name = "_ICQGCELEvents_AdvancedStudyInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyRemovedEventHandlerImpl(CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_advanced_study, index_};

            string name = "_ICQGCELEvents_AdvancedStudyRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyResolvedEventHandlerImpl(CQGAdvancedStudy cqg_advanced_study, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_advanced_study, cqg_error};

            string name = "_ICQGCELEvents_AdvancedStudyResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AdvancedStudyUpdatedEventHandlerImpl(CQGAdvancedStudy cqg_advanced_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_advanced_study, index_};

            string name = "_ICQGCELEvents_AdvancedStudyUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderPlacedEventHandlerImpl(string guid_, CQGAlgorithmicOrderParameters main_params, CQGAlgorithmicOrderProperties custom_props)
        {
            object[] args = new object[4] {"!", guid_, main_params, custom_props};

            string name = "_ICQGCELEvents_AlgorithmicOrderPlacedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandlerImpl(string guid_, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", guid_, cqg_error};

            string name = "_ICQGCELEvents_AlgorithmicOrderRegistrationCompleteEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AllOrdersCanceledEventHandlerImpl(eOrderSideFilter order_side, CQGIntegerCollection gw_account_ids, CQGStringCollection instrument_names)
        {
            object[] args = new object[4] {"!", order_side, gw_account_ids, instrument_names};

            string name = "_ICQGCELEvents_AllOrdersCanceledEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_AuthenticationStatusChangedEventHandlerImpl(eSessionStatus new_status, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", new_status, cqg_error};

            string name = "_ICQGCELEvents_AuthenticationStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_BarsTimestampsResolvedEventHandlerImpl(CQGBarsTimestamps cqg_bars_timestamps, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_bars_timestamps, cqg_error};

            string name = "_ICQGCELEvents_BarsTimestampsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_CELStartedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_CommodityInstrumentsResolvedEventHandlerImpl(string commodity_name, eInstrumentType instrument_types, CQGCommodityInstruments cqg_commodity_intruments)
        {
            object[] args = new object[4] {"!", commodity_name, instrument_types, cqg_commodity_intruments};

            string name = "_ICQGCELEvents_CommodityInstrumentsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionAddedEventHandlerImpl(CQGCondition cqg_condition)
        {
            object[] args = new object[2] {"!", cqg_condition};

            string name = "_ICQGCELEvents_ConditionAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionDefinitionsResolvedEventHandlerImpl(CQGConditionDefinitions cqg_condition_definitions, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_condition_definitions, cqg_error};

            string name = "_ICQGCELEvents_ConditionDefinitionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionInsertedEventHandlerImpl(CQGCondition cqg_condition, int index_)
        {
            object[] args = new object[3] {"!", cqg_condition, index_};

            string name = "_ICQGCELEvents_ConditionInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionRemovedEventHandlerImpl(CQGCondition cqg_condition, int index_)
        {
            object[] args = new object[3] {"!", cqg_condition, index_};

            string name = "_ICQGCELEvents_ConditionRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionResolvedEventHandlerImpl(CQGCondition cqg_condition, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_condition, cqg_error};

            string name = "_ICQGCELEvents_ConditionResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConditionUpdatedEventHandlerImpl(CQGCondition cqg_condition, int index_)
        {
            object[] args = new object[3] {"!", cqg_condition, index_};

            string name = "_ICQGCELEvents_ConditionUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsAddedEventHandlerImpl(CQGConstantVolumeBars cqg_constant_volume_bars)
        {
            object[] args = new object[2] {"!", cqg_constant_volume_bars};

            string name = "_ICQGCELEvents_ConstantVolumeBarsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsInsertedEventHandlerImpl(CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_constant_volume_bars, index_};

            string name = "_ICQGCELEvents_ConstantVolumeBarsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsRemovedEventHandlerImpl(CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_constant_volume_bars, index_};

            string name = "_ICQGCELEvents_ConstantVolumeBarsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsResolvedEventHandlerImpl(CQGConstantVolumeBars cqg_constant_volume_bars, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_constant_volume_bars, cqg_error};

            string name = "_ICQGCELEvents_ConstantVolumeBarsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandlerImpl(CQGConstantVolumeBars cqg_constant_volume_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_constant_volume_bars, index_};

            string name = "_ICQGCELEvents_ConstantVolumeBarsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CurrencyRatesChangedEventHandlerImpl(CQGCurrencyRates cqg_currency_rates)
        {
            object[] args = new object[2] {"!", cqg_currency_rates};

            string name = "_ICQGCELEvents_CurrencyRatesChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomSessionsResolvedEventHandlerImpl(CQGSessionsCollection cqg_sessions_collection, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_sessions_collection, cqg_error};

            string name = "_ICQGCELEvents_CustomSessionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyAddedEventHandlerImpl(CQGCustomStudy cqg_custom_study)
        {
            object[] args = new object[2] {"!", cqg_custom_study};

            string name = "_ICQGCELEvents_CustomStudyAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandlerImpl(CQGCustomStudyDefinitions cqg_custom_study_definitions, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_custom_study_definitions, cqg_error};

            string name = "_ICQGCELEvents_CustomStudyDefinitionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyInsertedEventHandlerImpl(CQGCustomStudy cqg_custom_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_custom_study, index_};

            string name = "_ICQGCELEvents_CustomStudyInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyRemovedEventHandlerImpl(CQGCustomStudy cqg_custom_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_custom_study, index_};

            string name = "_ICQGCELEvents_CustomStudyRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyResolvedEventHandlerImpl(CQGCustomStudy cqg_custom_study, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_custom_study, cqg_error};

            string name = "_ICQGCELEvents_CustomStudyResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_CustomStudyUpdatedEventHandlerImpl(CQGCustomStudy cqg_custom_study, int index_)
        {
            object[] args = new object[3] {"!", cqg_custom_study, index_};

            string name = "_ICQGCELEvents_CustomStudyUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            object[] args = new object[2] {"!", new_status};

            string name = "_ICQGCELEvents_DataConnectionStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataErrorEventHandlerImpl(object cqg_error, string error_description)
        {
            object[] args = new object[3] {"!", cqg_error, error_description};

            string name = "_ICQGCELEvents_DataErrorEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataSourcesResolvedEventHandlerImpl(CQGDataSources cqg_data_sources, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_data_sources, cqg_error};

            string name = "_ICQGCELEvents_DataSourcesResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_DataSourceSymbolsResolvedEventHandlerImpl(string data_source_abbreviation, CQGDataSourceSymbols cqg_data_source_symbols, CQGError cqg_error)
        {
            object[] args = new object[4] {"!", data_source_abbreviation, cqg_data_source_symbols, cqg_error};

            string name = "_ICQGCELEvents_DataSourceSymbolsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionAddedEventHandlerImpl(CQGExpression cqg_expression)
        {
            object[] args = new object[2] {"!", cqg_expression};

            string name = "_ICQGCELEvents_ExpressionAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionInsertedEventHandlerImpl(CQGExpression cqg_expression, int index_)
        {
            object[] args = new object[3] {"!", cqg_expression, index_};

            string name = "_ICQGCELEvents_ExpressionInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionRemovedEventHandlerImpl(CQGExpression cqg_expression, int index_)
        {
            object[] args = new object[3] {"!", cqg_expression, index_};

            string name = "_ICQGCELEvents_ExpressionRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionResolvedEventHandlerImpl(CQGExpression cqg_expression, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_expression, cqg_error};

            string name = "_ICQGCELEvents_ExpressionResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ExpressionUpdatedEventHandlerImpl(CQGExpression cqg_expression, int index_)
        {
            object[] args = new object[3] {"!", cqg_expression, index_};

            string name = "_ICQGCELEvents_ExpressionUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_GWConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            object[] args = new object[2] {"!", new_status};

            string name = "_ICQGCELEvents_GWConnectionStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_GWEnvironmentChangedEventHandlerImpl(eGWEnvChangeCode event_code, int account_id, int phase_)
        {
            object[] args = new object[4] {"!", event_code, account_id, phase_};

            string name = "_ICQGCELEvents_GWEnvironmentChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_HistoricalSessionsResolvedEventHandlerImpl(CQGSessionsCollection cqg_historical_sessions, CQGHistoricalSessionsRequest cqg_historical_sessions_request, CQGError cqg_error)
        {
            object[] args = new object[4] {"!", cqg_historical_sessions, cqg_historical_sessions_request, cqg_error};

            string name = "_ICQGCELEvents_HistoricalSessionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ICConnectionStatusChangedEventHandlerImpl(eICConnectionStatus new_status)
        {
            object[] args = new object[2] {"!", new_status};

            string name = "_ICQGCELEvents_ICConnectionStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_IncorrectSymbolEventHandlerImpl(string symbol_)
        {
            object[] args = new object[2] {"!", symbol_};

            string name = "_ICQGCELEvents_IncorrectSymbolEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentChangedEventHandlerImpl(CQGInstrument cqg_instrument, CQGQuotes cqg_quotes, CQGInstrumentProperties cqg_instrument_properties)
        {
            object[] args = new object[4] {"!", cqg_instrument, cqg_quotes, cqg_instrument_properties};

            string name = "_ICQGCELEvents_InstrumentChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentDOMChangedEventHandlerImpl(CQGInstrument cqg_instrument, CQGDOMQuotes prev_asks, CQGDOMQuotes prev_bids)
        {
            object[] args = new object[4] {"!", cqg_instrument, prev_asks, prev_bids};

            string name = "_ICQGCELEvents_InstrumentDOMChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentsGroupChangedEventHandlerImpl(eChangeType change_type, CQGInstrumentsGroup instruments_group, CQGStringCollection instruments_names)
        {
            object[] args = new object[4] {"!", change_type, instruments_group, instruments_names};

            string name = "_ICQGCELEvents_InstrumentsGroupChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentsGroupResolvedEventHandlerImpl(CQGInstrumentsGroup instruments_group, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", instruments_group, cqg_error};

            string name = "_ICQGCELEvents_InstrumentsGroupResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_InstrumentSubscribedEventHandlerImpl(string symbol_, CQGInstrument cqg_instrument)
        {
            object[] args = new object[3] {"!", symbol_, cqg_instrument};

            string name = "_ICQGCELEvents_InstrumentSubscribedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_IsReadyEventHandlerImpl(ref eReadyStatus ready_status)
        {
            object[] args = new object[2] {"!", ready_status};

            string name = "_ICQGCELEvents_IsReadyEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            object[] args = new object[2] {"!", new_line_time};

            string name = "_ICQGCELEvents_LineTimeChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillChangedEventHandlerImpl(CQGManualFill cqg_manual_fill, eManualFillUpdateType modify_type)
        {
            object[] args = new object[3] {"!", cqg_manual_fill, modify_type};

            string name = "_ICQGCELEvents_ManualFillChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillsResolvedEventHandlerImpl(CQGManualFills cqg_manual_fills, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_manual_fills, cqg_error};

            string name = "_ICQGCELEvents_ManualFillsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_ManualFillUpdateResolvedEventHandlerImpl(CQGManualFillRequest cqg_manual_fill_request, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_manual_fill_request, cqg_error};

            string name = "_ICQGCELEvents_ManualFillUpdateResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELEvents_OnIdleEventHandler";
            FakeCQG.CQG.CommonEventHandler(name);
        }

        public static void _ICQGCELEvents_OnQueryProgressEventHandlerImpl(CQGOrdersQuery cqg_orders_query, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_orders_query, cqg_error};

            string name = "_ICQGCELEvents_OnQueryProgressEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_OrderChangedEventHandlerImpl(eChangeType change_type, CQGOrder cqg_order, CQGOrderProperties old_properties, CQGFill cqg_fill, CQGError cqg_error)
        {
            object[] args = new object[6] {"!", change_type, cqg_order, old_properties, cqg_fill, cqg_error};

            string name = "_ICQGCELEvents_OrderChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PasswordChangedEventHandlerImpl(eSessionStatus request_status, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", request_status, cqg_error};

            string name = "_ICQGCELEvents_PasswordChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsAddedEventHandlerImpl(CQGPointAndFigureBars cqg_point_and_figure_bars)
        {
            object[] args = new object[2] {"!", cqg_point_and_figure_bars};

            string name = "_ICQGCELEvents_PointAndFigureBarsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsInsertedEventHandlerImpl(CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_point_and_figure_bars, index_};

            string name = "_ICQGCELEvents_PointAndFigureBarsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsRemovedEventHandlerImpl(CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_point_and_figure_bars, index_};

            string name = "_ICQGCELEvents_PointAndFigureBarsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsResolvedEventHandlerImpl(CQGPointAndFigureBars cqg_point_and_figure_bars, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_point_and_figure_bars, cqg_error};

            string name = "_ICQGCELEvents_PointAndFigureBarsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PointAndFigureBarsUpdatedEventHandlerImpl(CQGPointAndFigureBars cqg_point_and_figure_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_point_and_figure_bars, index_};

            string name = "_ICQGCELEvents_PointAndFigureBarsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_PositionsStatementResolvedEventHandlerImpl(CQGPositionsStatement cqg_positions_statement, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_positions_statement, cqg_error};

            string name = "_ICQGCELEvents_PositionsStatementResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_QFormulaDefinitionsResolvedEventHandlerImpl(CQGQFormulaDefinitions cqg_qformula_definitions, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_qformula_definitions, cqg_error};

            string name = "_ICQGCELEvents_QFormulaDefinitionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_StrategyDefinitionProgressEventHandlerImpl(CQGStrategyDefinition cqg_definition, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_definition, cqg_error};

            string name = "_ICQGCELEvents_StrategyDefinitionProgressEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsAddedEventHandlerImpl(CQGSubMinuteBars cqg_submintue_bars)
        {
            object[] args = new object[2] {"!", cqg_submintue_bars};

            string name = "_ICQGCELEvents_SubMinuteBarsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsInsertedEventHandlerImpl(CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_subminute_bars, index_};

            string name = "_ICQGCELEvents_SubMinuteBarsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsRemovedEventHandlerImpl(CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_subminute_bars, index_};

            string name = "_ICQGCELEvents_SubMinuteBarsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsResolvedEventHandlerImpl(CQGSubMinuteBars cqg_subminte_bars, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_subminte_bars, cqg_error};

            string name = "_ICQGCELEvents_SubMinuteBarsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SubMinuteBarsUpdatedEventHandlerImpl(CQGSubMinuteBars cqg_subminute_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_subminute_bars, index_};

            string name = "_ICQGCELEvents_SubMinuteBarsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_SummariesStatementResolvedEventHandlerImpl(CQGSummariesStatement cqg_summaries_statement, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_summaries_statement, cqg_error};

            string name = "_ICQGCELEvents_SummariesStatementResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsAddedEventHandlerImpl(CQGTFlowBars cqg_tflow_bars)
        {
            object[] args = new object[2] {"!", cqg_tflow_bars};

            string name = "_ICQGCELEvents_TFlowBarsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsInsertedEventHandlerImpl(CQGTFlowBars cqg_tflow_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_tflow_bars, index_};

            string name = "_ICQGCELEvents_TFlowBarsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsRemovedEventHandlerImpl(CQGTFlowBars cqg_tflow_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_tflow_bars, index_};

            string name = "_ICQGCELEvents_TFlowBarsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsResolvedEventHandlerImpl(CQGTFlowBars cqg_tflow_bars, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_tflow_bars, cqg_error};

            string name = "_ICQGCELEvents_TFlowBarsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TFlowBarsUpdatedEventHandlerImpl(CQGTFlowBars cqg_tflow_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_tflow_bars, index_};

            string name = "_ICQGCELEvents_TFlowBarsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TicksAddedEventHandlerImpl(CQGTicks cqg_ticks, int added_ticks_count)
        {
            object[] args = new object[3] {"!", cqg_ticks, added_ticks_count};

            string name = "_ICQGCELEvents_TicksAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TicksResolvedEventHandlerImpl(CQGTicks cqg_ticks, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_ticks, cqg_error};

            string name = "_ICQGCELEvents_TicksResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsAddedEventHandlerImpl(CQGTimedBars cqg_timed_bars)
        {
            object[] args = new object[2] {"!", cqg_timed_bars};

            string name = "_ICQGCELEvents_TimedBarsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsInsertedEventHandlerImpl(CQGTimedBars cqg_timed_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_timed_bars, index_};

            string name = "_ICQGCELEvents_TimedBarsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsRemovedEventHandlerImpl(CQGTimedBars cqg_timed_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_timed_bars, index_};

            string name = "_ICQGCELEvents_TimedBarsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsResolvedEventHandlerImpl(CQGTimedBars cqg_timed_bars, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_timed_bars, cqg_error};

            string name = "_ICQGCELEvents_TimedBarsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TimedBarsUpdatedEventHandlerImpl(CQGTimedBars cqg_timed_bars, int index_)
        {
            object[] args = new object[3] {"!", cqg_timed_bars, index_};

            string name = "_ICQGCELEvents_TimedBarsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradableCommoditiesResolvedEventHandlerImpl(int gw_account_id, CQGCommodities cqg_commodities, CQGError cqg_error)
        {
            object[] args = new object[4] {"!", gw_account_id, cqg_commodities, cqg_error};

            string name = "_ICQGCELEvents_TradableCommoditiesResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradableExchangesResolvedEventHandlerImpl(int gw_account_id, CQGExchanges cqg_exchanges, CQGError cqg_error)
        {
            object[] args = new object[4] {"!", gw_account_id, cqg_exchanges, cqg_error};

            string name = "_ICQGCELEvents_TradableExchangesResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemAddNotificationEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGTradingSystemAddInfo cqg_trading_system_add_info)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_trading_system_add_info};

            string name = "_ICQGCELEvents_TradingSystemAddNotificationEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandlerImpl(CQGTradingSystemDefinitions cqg_trading_system_definitions, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_trading_system_definitions, cqg_error};

            string name = "_ICQGCELEvents_TradingSystemDefinitionsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemInsertNotificationEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGTradingSystemInsertInfo cqg_trading_system_insert_info)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_trading_system_insert_info};

            string name = "_ICQGCELEvents_TradingSystemInsertNotificationEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemRemoveNotificationEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGTradingSystemRemoveInfo cqg_trading_system_remove_info)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_trading_system_remove_info};

            string name = "_ICQGCELEvents_TradingSystemRemoveNotificationEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemResolvedEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_error};

            string name = "_ICQGCELEvents_TradingSystemResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGTradingSystemRelationAddInfo cqg_trading_system_relation_add_info)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_trading_system_relation_add_info};

            string name = "_ICQGCELEvents_TradingSystemTradeRelationAddNotificationEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_TradingSystemUpdateNotificationEventHandlerImpl(CQGTradingSystem cqg_trading_system, CQGTradingSystemUpdateInfo cqg_trading_system_update_info)
        {
            object[] args = new object[3] {"!", cqg_trading_system, cqg_trading_system_update_info};

            string name = "_ICQGCELEvents_TradingSystemUpdateNotificationEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsAddedEventHandlerImpl(CQGYields cqg_yields)
        {
            object[] args = new object[2] {"!", cqg_yields};

            string name = "_ICQGCELEvents_YieldsAddedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsInsertedEventHandlerImpl(CQGYields cqg_yields, int index_)
        {
            object[] args = new object[3] {"!", cqg_yields, index_};

            string name = "_ICQGCELEvents_YieldsInsertedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsRemovedEventHandlerImpl(CQGYields cqg_yields, int index_)
        {
            object[] args = new object[3] {"!", cqg_yields, index_};

            string name = "_ICQGCELEvents_YieldsRemovedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsResolvedEventHandlerImpl(CQGYields cqg_yields, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", cqg_yields, cqg_error};

            string name = "_ICQGCELEvents_YieldsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELEvents_YieldsUpdatedEventHandlerImpl(CQGYields cqg_yields, int index_)
        {
            object[] args = new object[3] {"!", cqg_yields, index_};

            string name = "_ICQGCELEvents_YieldsUpdatedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_CELStartedEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_CELStartedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name);
        }

        public static void _ICQGCELGeneralEvents_CurrencyRatesChangedEventHandlerImpl(CQGCurrencyRates cqg_currency_rates)
        {
            object[] args = new object[2] {"!", cqg_currency_rates};

            string name = "_ICQGCELGeneralEvents_CurrencyRatesChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            object[] args = new object[2] {"!", new_status};

            string name = "_ICQGCELGeneralEvents_DataConnectionStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_DataErrorEventHandlerImpl(object cqg_error, string error_description)
        {
            object[] args = new object[3] {"!", cqg_error, error_description};

            string name = "_ICQGCELGeneralEvents_DataErrorEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandlerImpl(eConnectionStatus new_status)
        {
            object[] args = new object[2] {"!", new_status};

            string name = "_ICQGCELGeneralEvents_GWConnectionStatusChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_IsReadyEventHandlerImpl(ref eReadyStatus ready_status)
        {
            object[] args = new object[2] {"!", ready_status};

            string name = "_ICQGCELGeneralEvents_IsReadyEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_LineTimeChangedEventHandlerImpl(DateTime new_line_time)
        {
            object[] args = new object[2] {"!", new_line_time};

            string name = "_ICQGCELGeneralEvents_LineTimeChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELGeneralEvents_OnIdleEventHandlerImpl()
        {
            string name = "_ICQGCELGeneralEvents_OnIdleEventHandler";
            FakeCQG.CQG.CommonEventHandler(name);
        }

        public static void _ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandlerImpl(string commodity_name, eInstrumentType instrument_types, CQGCommodityInstruments cqg_commodity_intruments)
        {
            object[] args = new object[4] {"!", commodity_name, instrument_types, cqg_commodity_intruments};

            string name = "_ICQGCELInstrumentEvents_CommodityInstrumentsResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_IncorrectSymbolEventHandlerImpl(string symbol_)
        {
            object[] args = new object[2] {"!", symbol_};

            string name = "_ICQGCELInstrumentEvents_IncorrectSymbolEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentChangedEventHandlerImpl(CQGInstrument cqg_instrument, CQGQuotes cqg_quotes, CQGInstrumentProperties cqg_instrument_properties)
        {
            object[] args = new object[4] {"!", cqg_instrument, cqg_quotes, cqg_instrument_properties};

            string name = "_ICQGCELInstrumentEvents_InstrumentChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandlerImpl(CQGInstrument cqg_instrument, CQGDOMQuotes prev_asks, CQGDOMQuotes prev_bids)
        {
            object[] args = new object[4] {"!", cqg_instrument, prev_asks, prev_bids};

            string name = "_ICQGCELInstrumentEvents_InstrumentDOMChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandlerImpl(eChangeType change_type, CQGInstrumentsGroup instruments_group, CQGStringCollection instruments_names)
        {
            object[] args = new object[4] {"!", change_type, instruments_group, instruments_names};

            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupChangedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandlerImpl(CQGInstrumentsGroup instruments_group, CQGError cqg_error)
        {
            object[] args = new object[3] {"!", instruments_group, cqg_error};

            string name = "_ICQGCELInstrumentEvents_InstrumentsGroupResolvedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

        public static void _ICQGCELInstrumentEvents_InstrumentSubscribedEventHandlerImpl(string symbol_, CQGInstrument cqg_instrument)
        {
            object[] args = new object[3] {"!", symbol_, cqg_instrument};

            string name = "_ICQGCELInstrumentEvents_InstrumentSubscribedEventHandler";
            FakeCQG.CQG.CommonEventHandler(name, args);
        }

    }
}
